/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { TransactionControllerService } from './services/transaction-controller.service';
import { ProjectControllerService } from './services/project-controller.service';
import { EsgControllerService } from './services/esg-controller.service';
import { CarbonHistoryControllerService } from './services/carbon-history-controller.service';
import { ProjectOwnerControllerService } from './services/project-owner-controller.service';
import { PaymentControllerService } from './services/payment-controller.service';
import { CarbonFootprintDataControllerService } from './services/carbon-footprint-data-controller.service';
import { CarbonControllerService } from './services/carbon-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    TransactionControllerService,
    ProjectControllerService,
    EsgControllerService,
    CarbonHistoryControllerService,
    ProjectOwnerControllerService,
    PaymentControllerService,
    CarbonFootprintDataControllerService,
    CarbonControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
