/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CarbonFootprintCreateDto } from './models/carbon-footprint-create-dto';
export type { CarbonFootprintData } from './models/carbon-footprint-data';
export type { CarbonFootprintDataDto } from './models/carbon-footprint-data-dto';
export type { CarbonFootprintHistory } from './models/carbon-footprint-history';
export type { CarbonFootprintHistoryDto } from './models/carbon-footprint-history-dto';
export type { CarbonFootprintModelRequest } from './models/carbon-footprint-model-request';
export type { CarbonOutput } from './models/carbon-output';
export type { CarbonResponse } from './models/carbon-response';
export type { CompanyOwner } from './models/company-owner';
export type { CreateCarbonFootprintHistoryDto } from './models/create-carbon-footprint-history-dto';
export type { CreateResponseDto } from './models/create-response-dto';
export type { CustomerInfo } from './models/customer-info';
export type { EsgOption } from './models/esg-option';
export type { EsgOptionDto } from './models/esg-option-dto';
export type { EsgQuestion } from './models/esg-question';
export type { EsgQuestionDto } from './models/esg-question-dto';
export type { EsgResponse } from './models/esg-response';
export type { EsgResponseDto } from './models/esg-response-dto';
export type { EsgResponsesByCategoryDto } from './models/esg-responses-by-category-dto';
export type { EsgResultDto } from './models/esg-result-dto';
export type { EventData } from './models/event-data';
export type { EventFootprintData } from './models/event-footprint-data';
export type { PageableObject } from './models/pageable-object';
export type { PageProject } from './models/page-project';
export type { PageTransactionDto } from './models/page-transaction-dto';
export type { PaymentRequest } from './models/payment-request';
export type { PaymentResponse } from './models/payment-response';
export type { Project } from './models/project';
export type { ProjectDto } from './models/project-dto';
export type { ProjectInsertDto } from './models/project-insert-dto';
export type { ProjectOwnerDto } from './models/project-owner-dto';
export type { ProjectUpdateDto } from './models/project-update-dto';
export type { Score } from './models/score';
export type { SortObject } from './models/sort-object';
export type { Transaction } from './models/transaction';
export type { TransactionDto } from './models/transaction-dto';
export type { TransactionInsertDto } from './models/transaction-insert-dto';
