export enum RoutesEnum {
  HOME = '',
  PORTEUR = 'project-assesment',
  ENERGIE = 'energy',
  CARBURANT = 'fuel',
  AERIENS = 'air-travel',
  FRET = 'freight',
  CONSOMMABLES = 'consumables',
  IMMOBILISATIONS = 'fixed_assets',
  PANNEAUX = 'panels',
  RESULTAT_CARBONE = 'carbon-result',
  ESG = 'esg',
  CARBONE = 'carbon-calculator',
  RESULT_ESG = 'esg-result',
  ARBORICULTURE = 'trees-plantation',
  MARKETPLACE = 'marketplace',
  PROJECT_DETAILS = 'details',
  CHECKOUT = 'checkout',
  PAYMENT = 'payment',
  NEW_PROJECT = 'new-project',
  RESOURCES = 'resources',
  INFO = 'general-information',
  MARKETPLACE_BLOG = 'marketplace-blog',
  CARBON_OFFSET_BLOG = 'carbon-offset-blog',
  CARBON_CO_BENEFITS_BLOG = 'carbon-co-benefits-blog',
  ROADMAP = 'roadmap',
  ESG_ASSESSMENT = 'esg-assessment',

  PREDICTION_INFO = 'prediction-info',
  HISTORICAL_CARBON_FORECAST = 'historical-carbon-forecast',
  EVENT_FOOTPRINT ='event-footprint',
  EVENT_FORM = 'event-form',
  EVENT_RESULT = 'event-result',
  TRANSACTIONS = 'transactions',
  EVENT_HISTORY= 'event-history',
  CARBON_HISTORY = 'carbon-history',
  ESG_HISTORY = 'esg-history',
  COMPANY_OWNER_FORM = 'company-owner',
  REGISTER_COMPANY_OWNER= 'register-company-owner',

}

