export enum RoutesEnum {
  HOME = '',
  PORTEUR = 'porteur',
  ENERGIE = 'energie',
  CARBURANT = 'car',
  AERIENS = 'aer',
  FRET = 'fret',
  CONSOMMABLES = 'cons',
  IMMOBILISATIONS = 'imob',
  PANNEAUX = 'pan',
  RESULTAT_CARBONE = 'resultat',
  ESG = 'esg',
  CARBONE = 'carbone',
  RESULT_ESG = 'esg-result',
  ARBORICULTURE = 'arb',
  PISTE = 'piste',
  MARKETPLACE = 'marketplace',
  PROJECT_DETAILS = 'details',
  CHECKOUT = 'checkout',
  PAYMENT = 'payment',
  NEW_PROJECT = 'new-project',
  RESOURCES = 'resources',
  INFO = 'info',
  MARKETPLACE_BLOG = 'marketplace-blog',
  CARBON_OFFSET_BLOG = 'carbon-offset-blog',
  CARBON_CO_BENEFITS_BLOG = 'carbon-co-benefits-blog',
  ROADMAP = 'roadmap',
  ESG_ASSESSMENT = 'esg-assessment',
  PREDICTION_INFO = 'prediction-info',
  HISTORICAL_CARBON_FORECAST = 'historical-carbon-forecast',
  EVENT_FOOTPRINT ='event-footprint',
  EVENT_FORM = 'event-form',
  EVENT_RESULT = 'event-result',
  TRANSACTIONS = 'transactions',
  EVENT_HISTORY= 'event-history',
  CARBON_HISTORY = 'carbon-history',
  ESG_HISTORY = 'esg-history',
  COMPANY_OWNER_FORM = 'company-owner',
  REGISTER_COMPANY_OWNER= 'register-company-owner',

}

