spring.application.name=Ecopilot
spring.datasource.url=jdbc:mysql://mysql-13412e03-oussamagrami03-7663.l.aivencloud.com:14638/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_mfIu_ISiAwzEGvXx7nC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

