spring:
  application:
    name: Ecopilot
  datasource:
    url: jdbc:mysql://mysql-13412e03-oussamagrami03-7663.l.aivencloud.com:14638/defaultdb
    username: avnadmin
    password: AVNS_mfIu_ISiAwzEGvXx7nC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://keycloak-custom-v25.onrender.com/realms/booksproject"
stripe:
  api:
    key: sk_test_51PXiywF8Z6bWeMKqcDN9MXuxRefQjhGucEbVV3TnLCQFepXXL0Q41msQoasi4qVgPOsXFuIgrgXRjH8leDDUoeLk00W7IXsAEj
  public:
    key: pk_test_51PXiywF8Z6bWeMKqugWRfPksVOGqhWanFvATWLFhIpB4yJ5Hh4hN6K0j0R9aAzEtEGZfvXPzjb9OZcOMntiQT39h00HzHCJWtl
logging:
  level:
    root: WARN   # This will only log WARN and ERROR messages globally.
    org.springframework.web: INFO   # Only INFO and higher for Spring Web
    org.springframework.orm.hibernate5: ERROR  # Set Hibernate to log only errors
flask:
  api:
    url: http://127.0.0.1:5000/
    url.enterprise: ${flask.api.url}generate-recommendations-entreprise
    url.event: ${flask.api.url}generate-recommendations-event
server:
  port: 8087
file:
  upload-dir: ./uploads