/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarbonFootprintDataDto } from '../../models/carbon-footprint-data-dto';

export interface GetByOwnerId$Params {
  ownerId: number;
}

export function getByOwnerId(http: HttpClient, rootUrl: string, params: GetByOwnerId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CarbonFootprintDataDto>>> {
  const rb = new RequestBuilder(rootUrl, getByOwnerId.PATH, 'get');
  if (params) {
    rb.path('ownerId', params.ownerId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CarbonFootprintDataDto>>;
    })
  );
}

getByOwnerId.PATH = '/api/carbon/owner/{ownerId}';
