version: '3.9'

services:
  backend:
    build:
      context: ./back/Ecopilot
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    restart: unless-stopped

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
  model:
    build:
      context: ./Model
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped