/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CarbonFootprintModelRequest {
  activity_sector?: string;
  annual_consumption_of_GPL?: number;
  annual_consumption_of_coal?: number;
  annual_consumption_of_electricity?: number;
  annual_consumption_of_fuel?: number;
  annual_consumption_of_natural_gas?: number;
  annual_consumption_of_propane?: number;
  annual_consumption_of_refrigerant?: number;
  built_area_of_company?: number;
  consumption_of_LPG?: number;
  country?: string;
  expenses_of_paper?: number;
  expenses_of_small_office_supplies?: number;
  fuel_consumption_of_diesel?: number;
  fuel_consumption_of_gasoline?: number;
  number_of_commercial_vehicles?: number;
  number_of_desktop_computers?: number;
  number_of_flat_panel_screens?: number;
  number_of_full_time_employees?: number;
  number_of_heavy_vehicles?: number;
  number_of_individual_printers?: number;
  number_of_laptops?: number;
  number_of_light_duty_vehicles?: number;
  number_of_long_haul_round_trip?: number;
  number_of_medium_haul_round_trip?: number;
  number_of_multifunction_printers?: number;
  number_of_servers?: number;
  number_of_short_haul_round_trip?: number;
  percentage_of_telework?: number;
  tons_of_air_freight_gt_3000?: number;
  tons_of_air_freight_lt_3000?: number;
  tons_of_sea_freight_gt_3000?: number;
  tons_of_sea_freight_lt_3000?: number;
}
