/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyOwner } from '../models/company-owner';
export interface CarbonFootprintHistory {
  companyOwner?: CompanyOwner;
  createdBy?: string;
  createdDate?: string;
  date?: {
'year'?: number;
'month'?: 'JANUARY' | 'FEBRUARY' | 'MARCH' | 'APRIL' | 'MAY' | 'JUNE' | 'JULY' | 'AUGUST' | 'SEPTEMBER' | 'OCTOBER' | 'NOVEMBER' | 'DECEMBER';
'monthValue'?: number;
'leapYear'?: boolean;
};
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  predicted?: boolean;
  value?: number;
}
