/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CarbonFootprintCreateDto {
  activitySector: string;
  annualConsumptionOfCoal?: number;
  annualConsumptionOfElectricity?: number;
  annualConsumptionOfFuel?: number;
  annualConsumptionOfGPL?: number;
  annualConsumptionOfNaturalGas?: number;
  annualConsumptionOfPropane?: number;
  annualConsumptionOfRefrigerant?: number;
  beginDate: string;
  builtAreaOfCompany?: number;
  carburantType?: 'DIESEL' | 'GASOLINE' | 'LPG';
  companyOwnerId: number;
  consumptionOfLPG?: number;
  country: string;
  drivenDistance?: number;
  endDate: string;
  expensesOnPaper?: number;
  expensesOnSmallOfficeSupplies?: number;
  fuelConsumptionOfDiesel?: number;
  fuelConsumptionOfGasoline?: number;
  numberOfCommercialVehicles?: number;
  numberOfDesktopComputers?: number;
  numberOfFlatPanelScreens?: number;
  numberOfFullTimeEmployees?: number;
  numberOfHeavyVehicles?: number;
  numberOfIndividualPrinters?: number;
  numberOfLaptops?: number;
  numberOfLightDutyVehicles?: number;
  numberOfLongHaulRoundTrips?: number;
  numberOfMediumHaulRoundTrips?: number;
  numberOfMultifunctionPrinters?: number;
  numberOfServers?: number;
  numberOfShortHaulRoundTrips?: number;
  percentageOfTelework?: number;
  tonsOfAirFreightLong?: number;
  tonsOfAirFreightShort?: number;
  tonsOfSeaFreightLong?: number;
  tonsOfSeaFreightShort?: number;
  unitFourniture?: 'DOLLAR' | 'EURO' | 'TUNISIAN_DINAR';
  unitPaper?: 'DOLLAR' | 'EURO' | 'TUNISIAN_DINAR';
  vehicleFuelEfficiency?: number;
}
