/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CarbonOutput } from '../models/carbon-output';
export interface CarbonResponse {
  recommendations?: Array<CarbonOutput>;
  status?: string;
}
