/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyOwner } from '../models/company-owner';
export interface CarbonFootprintData {
  activitySector?: string;
  aerienEmission?: number;
  annualConsumptionOfCoal?: number;
  annualConsumptionOfElectricity?: number;
  annualConsumptionOfFuel?: number;
  annualConsumptionOfGPL?: number;
  annualConsumptionOfNaturalGas?: number;
  annualConsumptionOfPropane?: number;
  annualConsumptionOfRefrigerant?: number;
  beginDate?: string;
  builtAreaOfCompany?: number;
  carburantEmissions?: number;
  carburantType?: 'DIESEL' | 'GASOLINE' | 'LPG';
  companyOwner?: CompanyOwner;
  consomableEmissions?: number;
  consumptionOfLPG?: number;
  country?: string;
  createdBy?: string;
  createdDate?: string;
  drivenDistance?: number;
  endDate?: string;
  energyEmissions?: number;
  expensesOnPaper?: number;
  expensesOnSmallOfficeSupplies?: number;
  freightEmission?: number;
  fuelConsumptionOfDiesel?: number;
  fuelConsumptionOfGasoline?: number;
  id?: number;
  immobilisationEmissions?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  numberOfCommercialVehicles?: number;
  numberOfDesktopComputers?: number;
  numberOfFlatPanelScreens?: number;
  numberOfFullTimeEmployees?: number;
  numberOfHeavyVehicles?: number;
  numberOfIndividualPrinters?: number;
  numberOfLaptops?: number;
  numberOfLightDutyVehicles?: number;
  numberOfLongHaulRoundTrips?: number;
  numberOfMediumHaulRoundTrips?: number;
  numberOfMultifunctionPrinters?: number;
  numberOfServers?: number;
  numberOfShortHaulRoundTrips?: number;
  percentageOfTelework?: number;
  tonsOfAirFreightLong?: number;
  tonsOfAirFreightShort?: number;
  tonsOfSeaFreightLong?: number;
  tonsOfSeaFreightShort?: number;
  totalEmissions?: number;
  unitFourniture?: 'DOLLAR' | 'EURO' | 'TUNISIAN_DINAR';
  unitPaper?: 'DOLLAR' | 'EURO' | 'TUNISIAN_DINAR';
  vehicleFuelEfficiency?: number;
}
