/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CarbonFootprintDataDto {
  aerienEmission?: number;
  beginDate?: string;
  carburantEmissions?: number;
  companyOwnerId?: number;
  companyOwnerName?: string;
  consomableEmissions?: number;
  createdDate?: string;
  endDate?: string;
  energyEmissions?: number;
  freightEmission?: number;
  immobilisationEmissions?: number;
  totalEmissions?: number;
}
