/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CarbonFootprintData } from '../models/carbon-footprint-data';
import { CarbonFootprintHistory } from '../models/carbon-footprint-history';
import { EsgResponse } from '../models/esg-response';
import { EventFootprintData } from '../models/event-footprint-data';
import { Score } from '../models/score';
import { Transaction } from '../models/transaction';
export interface CompanyOwner {
  carbonFootprintData?: Array<CarbonFootprintData>;
  carboneFootprintHistory?: Array<CarbonFootprintHistory>;
  companyCode?: string;
  companyName?: string;
  country?: number;
  createdBy?: string;
  createdDate?: string;
  domaine?: string;
  email?: string;
  esgResponses?: Array<EsgResponse>;
  eventFootprintData?: Array<EventFootprintData>;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  nom?: string;
  numTelephone?: number;
  password?: string;
  role?: 'ROLE_CEO' | 'ROLE_MANAGER' | 'ROLE_EMPLOYEE';
  scores?: Array<Score>;
  transactions?: Array<Transaction>;
}
