/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCarbonFootprintHistoryDto {
  date?: {
'year'?: number;
'month'?: 'JANUARY' | 'FEBRUARY' | 'MARCH' | 'APRIL' | 'MAY' | 'JUNE' | 'JULY' | 'AUGUST' | 'SEPTEMBER' | 'OCTOBER' | 'NOVEMBER' | 'DECEMBER';
'monthValue'?: number;
'leapYear'?: boolean;
};
  predicted?: boolean;
  value?: number;
}
