/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerInfo {
  address?: string;
  city?: string;
  country?: string;
  email?: string;
  phone?: string;
  postalCode?: string;
  province?: string;
}
