/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyOwner } from '../models/company-owner';
import { EsgOption } from '../models/esg-option';
import { EsgQuestion } from '../models/esg-question';
export interface EsgResponse {
  companyOwner?: CompanyOwner;
  createdBy?: string;
  createdDate?: string;
  esgOption?: EsgOption;
  esgQuestion?: EsgQuestion;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
}
