/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EsgOption } from '../models/esg-option';
import { EsgResponse } from '../models/esg-response';
export interface EsgQuestion {
  category?: 'ENVIRONMENTAL' | 'SOCIAL' | 'GOVERNANCE';
  createdBy?: string;
  createdDate?: string;
  esgOptions?: Array<EsgOption>;
  esgResponses?: Array<EsgResponse>;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  text?: string;
}
