/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EsgResponseDto } from '../models/esg-response-dto';
export interface EsgResponsesByCategoryDto {
  category?: 'ENVIRONMENTAL' | 'SOCIAL' | 'GOVERNANCE';
  response?: Array<EsgResponseDto>;
}
