/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EsgOptionDto } from '../models/esg-option-dto';
export interface EsgQuestionDto {
  category?: 'ENVIRONMENTAL' | 'SOCIAL' | 'GOVERNANCE';
  id?: number;
  options?: Array<EsgOptionDto>;
  text?: string;
}
