/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EsgQuestion } from '../models/esg-question';
import { EsgResponse } from '../models/esg-response';
export interface EsgOption {
  createdBy?: string;
  createdDate?: string;
  esgQuestion?: EsgQuestion;
  esgResponses?: Array<EsgResponse>;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  score?: number;
  text?: string;
}
