/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventData {
  attendeesUsingTransport?: number;
  avgPowerPerDevice?: number;
  decorationMaterial?: number;
  duration?: number;
  energyUsageHours?: number;
  eventName?: string;
  eventType?: string;
  location?: string;
  mealType?: string;
  numberOfDevices?: number;
  numberOfMeals?: number;
  participants?: number;
  printedMaterial?: number;
  totalEmissions?: number;
  transportDistance?: number;
  transportMode?: string;
  venueType?: string;
}
