/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyOwner } from '../models/company-owner';
export interface EventFootprintData {
  attendeesUsingTransport?: number;
  avgPowerPerDevice?: number;
  companyOwner?: CompanyOwner;
  createdBy?: string;
  createdDate?: string;
  decorationMaterial?: number;
  deviceNbr?: number;
  duration?: number;
  energyUsageHours?: number;
  eventName?: string;
  eventType?: string;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  location?: string;
  melType?: string;
  nbrOfMeals?: number;
  participantsNbr?: number;
  printedMaterial?: number;
  totalEmission?: number;
  transportDistance?: number;
  transportMode?: string;
  venueType?: string;
}
