/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomerInfo } from '../models/customer-info';
export interface PaymentRequest {
  amount?: number;
  cartLineIds?: Array<number>;
  companyOwnerId?: number;
  currency?: string;
  customerInfo?: CustomerInfo;
  description?: string;
  totalPrice?: string;
}
