/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Project {
  availableStock?: number;
  category?: string;
  certified?: boolean;
  cost?: number;
  country?: string;
  createdBy?: string;
  createdDate?: string;
  description?: string;
  flag?: string;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  mapUrl?: string;
  mechanism?: string;
  minimumPurchase?: number;
  name?: string;
  routing?: string;
  typeOfProject?: string;
  url?: string;
}
