/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectOwnerDto {
  certified?: boolean;
  company?: string;
  companyIdentifier?: string;
  description?: string;
  email?: string;
  estimation?: boolean;
  estimationValue?: number;
  firstname?: string;
  id?: number;
  job_function?: string;
  nom: string;
  password?: string;
  phone?: string;
  projectIds?: Array<number>;
  region?: string;
  website?: string;
}
