/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectDto {
  availableStock?: number;
  category?: string;
  certified?: boolean;
  chartLinesIds?: Array<number>;
  cost?: number;
  country?: string;
  description?: string;
  flag?: string;
  id?: number;
  mapUrl?: string;
  mechanism?: string;
  minimumPurchase?: number;
  name?: string;
  projectOwnerId?: number;
  routing?: string;
  typeOfProject?: string;
  url?: string;
}
