/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyOwner } from '../models/company-owner';
export interface Score {
  annee?: number;
  companyOwner?: CompanyOwner;
  createdBy?: string;
  createdDate?: string;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  valuer?: number;
}
