/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Transaction {
  address?: string;
  city?: string;
  country?: string;
  createdBy?: string;
  createdDate?: string;
  description?: string;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  phone?: string;
  postalCode?: number;
  province?: string;
  totalPrice?: number;
}
