/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionDto {
  address?: string;
  chartLineIds?: Array<number>;
  city?: string;
  companyOwnerId?: number;
  country?: string;
  createdAt?: string;
  description?: string;
  id?: number;
  phone?: string;
  postalCode?: number;
  province?: string;
  totalPrice?: number;
}
