/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarbonResponse } from '../../models/carbon-response';
import { EventData } from '../../models/event-data';

export interface GenerateRecommendationsEvent$Params {
      body: EventData
}

export function generateRecommendationsEvent(http: HttpClient, rootUrl: string, params: GenerateRecommendationsEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<CarbonResponse>> {
  const rb = new RequestBuilder(rootUrl, generateRecommendationsEvent.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CarbonResponse>;
    })
  );
}

generateRecommendationsEvent.PATH = '/api/carbon/ai/generate-recommendations-event';
