/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarbonFootprintModelRequest } from '../../models/carbon-footprint-model-request';
import { CarbonResponse } from '../../models/carbon-response';

export interface GenerateRecommendations$Params {
      body: CarbonFootprintModelRequest
}

export function generateRecommendations(http: HttpClient, rootUrl: string, params: GenerateRecommendations$Params, context?: HttpContext): Observable<StrictHttpResponse<CarbonResponse>> {
  const rb = new RequestBuilder(rootUrl, generateRecommendations.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CarbonResponse>;
    })
  );
}

generateRecommendations.PATH = '/api/carbon/ai/recommendations';
