/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EsgResultDto } from '../../models/esg-result-dto';

export interface CalculateEsg$Params {
}

export function calculateEsg(http: HttpClient, rootUrl: string, params?: CalculateEsg$Params, context?: HttpContext): Observable<StrictHttpResponse<EsgResultDto>> {
  const rb = new RequestBuilder(rootUrl, calculateEsg.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EsgResultDto>;
    })
  );
}

calculateEsg.PATH = '/esg/calculate';
