/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EsgQuestionDto } from '../../models/esg-question-dto';

export interface GetEsgQuestionById$Params {
  questionId: number;
}

export function getEsgQuestionById(http: HttpClient, rootUrl: string, params: GetEsgQuestionById$Params, context?: HttpContext): Observable<StrictHttpResponse<EsgQuestionDto>> {
  const rb = new RequestBuilder(rootUrl, getEsgQuestionById.PATH, 'get');
  if (params) {
    rb.path('questionId', params.questionId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EsgQuestionDto>;
    })
  );
}

getEsgQuestionById.PATH = '/esg/question/{questionId}';
