/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EsgQuestionDto } from '../../models/esg-question-dto';

export interface GetQuestionsByCategory$Params {
  category: string;
}

export function getQuestionsByCategory(http: HttpClient, rootUrl: string, params: GetQuestionsByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EsgQuestionDto>>> {
  const rb = new RequestBuilder(rootUrl, getQuestionsByCategory.PATH, 'get');
  if (params) {
    rb.path('category', params.category, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EsgQuestionDto>>;
    })
  );
}

getQuestionsByCategory.PATH = '/esg/questions/{category}';
