/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateResponseDto } from '../../models/create-response-dto';
import { EsgResponse } from '../../models/esg-response';

export interface SaveEsgResponse$Params {
      body: CreateResponseDto
}

export function saveEsgResponse(http: HttpClient, rootUrl: string, params: SaveEsgResponse$Params, context?: HttpContext): Observable<StrictHttpResponse<EsgResponse>> {
  const rb = new RequestBuilder(rootUrl, saveEsgResponse.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EsgResponse>;
    })
  );
}

saveEsgResponse.PATH = '/esg/responses';
