/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CarbonResponse } from '../models/carbon-response';
import { generateRecommendations } from '../fn/carbon-controller/generate-recommendations';
import { GenerateRecommendations$Params } from '../fn/carbon-controller/generate-recommendations';
import { generateRecommendationsEvent } from '../fn/carbon-controller/generate-recommendations-event';
import { GenerateRecommendationsEvent$Params } from '../fn/carbon-controller/generate-recommendations-event';

@Injectable({ providedIn: 'root' })
export class CarbonControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `generateRecommendations()` */
  static readonly GenerateRecommendationsPath = '/api/carbon/ai/recommendations';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateRecommendations()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  generateRecommendations$Response(params: GenerateRecommendations$Params, context?: HttpContext): Observable<StrictHttpResponse<CarbonResponse>> {
    return generateRecommendations(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateRecommendations$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  generateRecommendations(params: GenerateRecommendations$Params, context?: HttpContext): Observable<CarbonResponse> {
    return this.generateRecommendations$Response(params, context).pipe(
      map((r: StrictHttpResponse<CarbonResponse>): CarbonResponse => r.body)
    );
  }

  /** Path part for operation `generateRecommendationsEvent()` */
  static readonly GenerateRecommendationsEventPath = '/api/carbon/ai/generate-recommendations-event';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateRecommendationsEvent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  generateRecommendationsEvent$Response(params: GenerateRecommendationsEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<CarbonResponse>> {
    return generateRecommendationsEvent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateRecommendationsEvent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  generateRecommendationsEvent(params: GenerateRecommendationsEvent$Params, context?: HttpContext): Observable<CarbonResponse> {
    return this.generateRecommendationsEvent$Response(params, context).pipe(
      map((r: StrictHttpResponse<CarbonResponse>): CarbonResponse => r.body)
    );
  }

}
