/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CarbonFootprintHistoryDto } from '../models/carbon-footprint-history-dto';
import { createAllCarbonHistory } from '../fn/carbon-history-controller/create-all-carbon-history';
import { CreateAllCarbonHistory$Params } from '../fn/carbon-history-controller/create-all-carbon-history';
import { createCarbonHistory } from '../fn/carbon-history-controller/create-carbon-history';
import { CreateCarbonHistory$Params } from '../fn/carbon-history-controller/create-carbon-history';
import { deleteCarbonHistory } from '../fn/carbon-history-controller/delete-carbon-history';
import { DeleteCarbonHistory$Params } from '../fn/carbon-history-controller/delete-carbon-history';
import { forecastData } from '../fn/carbon-history-controller/forecast-data';
import { ForecastData$Params } from '../fn/carbon-history-controller/forecast-data';
import { getAllCarbonHistory } from '../fn/carbon-history-controller/get-all-carbon-history';
import { GetAllCarbonHistory$Params } from '../fn/carbon-history-controller/get-all-carbon-history';
import { updateCarbonHistory } from '../fn/carbon-history-controller/update-carbon-history';
import { UpdateCarbonHistory$Params } from '../fn/carbon-history-controller/update-carbon-history';

@Injectable({ providedIn: 'root' })
export class CarbonHistoryControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateCarbonHistory()` */
  static readonly UpdateCarbonHistoryPath = '/carbonHistory/update/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCarbonHistory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCarbonHistory$Response(params: UpdateCarbonHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateCarbonHistory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCarbonHistory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCarbonHistory(params: UpdateCarbonHistory$Params, context?: HttpContext): Observable<void> {
    return this.updateCarbonHistory$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `createCarbonHistory()` */
  static readonly CreateCarbonHistoryPath = '/carbonHistory/save';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCarbonHistory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCarbonHistory$Response(params: CreateCarbonHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return createCarbonHistory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCarbonHistory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCarbonHistory(params: CreateCarbonHistory$Params, context?: HttpContext): Observable<void> {
    return this.createCarbonHistory$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `createAllCarbonHistory()` */
  static readonly CreateAllCarbonHistoryPath = '/carbonHistory/saveAll';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createAllCarbonHistory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAllCarbonHistory$Response(params: CreateAllCarbonHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return createAllCarbonHistory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createAllCarbonHistory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createAllCarbonHistory(params: CreateAllCarbonHistory$Params, context?: HttpContext): Observable<void> {
    return this.createAllCarbonHistory$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `forecastData()` */
  static readonly ForecastDataPath = '/carbonHistory/forecast';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `forecastData()` instead.
   *
   * This method doesn't expect any request body.
   */
  forecastData$Response(params?: ForecastData$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CarbonFootprintHistoryDto>>> {
    return forecastData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `forecastData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  forecastData(params?: ForecastData$Params, context?: HttpContext): Observable<Array<CarbonFootprintHistoryDto>> {
    return this.forecastData$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CarbonFootprintHistoryDto>>): Array<CarbonFootprintHistoryDto> => r.body)
    );
  }

  /** Path part for operation `getAllCarbonHistory()` */
  static readonly GetAllCarbonHistoryPath = '/carbonHistory/all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCarbonHistory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCarbonHistory$Response(params?: GetAllCarbonHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CarbonFootprintHistoryDto>>> {
    return getAllCarbonHistory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCarbonHistory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCarbonHistory(params?: GetAllCarbonHistory$Params, context?: HttpContext): Observable<Array<CarbonFootprintHistoryDto>> {
    return this.getAllCarbonHistory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CarbonFootprintHistoryDto>>): Array<CarbonFootprintHistoryDto> => r.body)
    );
  }

  /** Path part for operation `deleteCarbonHistory()` */
  static readonly DeleteCarbonHistoryPath = '/carbonHistory/delete/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCarbonHistory()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCarbonHistory$Response(params: DeleteCarbonHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteCarbonHistory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCarbonHistory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCarbonHistory(params: DeleteCarbonHistory$Params, context?: HttpContext): Observable<void> {
    return this.deleteCarbonHistory$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
