/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CarbonFootprintDataDto } from '../models/carbon-footprint-data-dto';
import { create2 } from '../fn/carbon-footprint-data-controller/create-2';
import { Create2$Params } from '../fn/carbon-footprint-data-controller/create-2';
import { delete$ } from '../fn/carbon-footprint-data-controller/delete';
import { Delete$Params } from '../fn/carbon-footprint-data-controller/delete';
import { getAll2 } from '../fn/carbon-footprint-data-controller/get-all-2';
import { GetAll2$Params } from '../fn/carbon-footprint-data-controller/get-all-2';
import { getById3 } from '../fn/carbon-footprint-data-controller/get-by-id-3';
import { GetById3$Params } from '../fn/carbon-footprint-data-controller/get-by-id-3';
import { getByOwnerId } from '../fn/carbon-footprint-data-controller/get-by-owner-id';
import { GetByOwnerId$Params } from '../fn/carbon-footprint-data-controller/get-by-owner-id';

@Injectable({ providedIn: 'root' })
export class CarbonFootprintDataControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAll2()` */
  static readonly GetAll2Path = '/api/carbon';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll2()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll2$Response(params?: GetAll2$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CarbonFootprintDataDto>>> {
    return getAll2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll2(params?: GetAll2$Params, context?: HttpContext): Observable<Array<CarbonFootprintDataDto>> {
    return this.getAll2$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CarbonFootprintDataDto>>): Array<CarbonFootprintDataDto> => r.body)
    );
  }

  /** Path part for operation `create2()` */
  static readonly Create2Path = '/api/carbon';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create2$Response(params: Create2$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return create2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create2(params: Create2$Params, context?: HttpContext): Observable<void> {
    return this.create2$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getById3()` */
  static readonly GetById3Path = '/api/carbon/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById3()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById3$Response(params: GetById3$Params, context?: HttpContext): Observable<StrictHttpResponse<CarbonFootprintDataDto>> {
    return getById3(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById3$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById3(params: GetById3$Params, context?: HttpContext): Observable<CarbonFootprintDataDto> {
    return this.getById3$Response(params, context).pipe(
      map((r: StrictHttpResponse<CarbonFootprintDataDto>): CarbonFootprintDataDto => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/api/carbon/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete$(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<void> {
    return this.delete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getByOwnerId()` */
  static readonly GetByOwnerIdPath = '/api/carbon/owner/{ownerId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getByOwnerId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getByOwnerId$Response(params: GetByOwnerId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CarbonFootprintDataDto>>> {
    return getByOwnerId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getByOwnerId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getByOwnerId(params: GetByOwnerId$Params, context?: HttpContext): Observable<Array<CarbonFootprintDataDto>> {
    return this.getByOwnerId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CarbonFootprintDataDto>>): Array<CarbonFootprintDataDto> => r.body)
    );
  }

}
