/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { calculateEsg } from '../fn/esg-controller/calculate-esg';
import { CalculateEsg$Params } from '../fn/esg-controller/calculate-esg';
import { createEsgQuestion } from '../fn/esg-controller/create-esg-question';
import { CreateEsgQuestion$Params } from '../fn/esg-controller/create-esg-question';
import { deleteEsgQuestion } from '../fn/esg-controller/delete-esg-question';
import { DeleteEsgQuestion$Params } from '../fn/esg-controller/delete-esg-question';
import { deleteEsgResponse } from '../fn/esg-controller/delete-esg-response';
import { DeleteEsgResponse$Params } from '../fn/esg-controller/delete-esg-response';
import { EsgQuestionDto } from '../models/esg-question-dto';
import { EsgResponse } from '../models/esg-response';
import { EsgResponsesByCategoryDto } from '../models/esg-responses-by-category-dto';
import { EsgResultDto } from '../models/esg-result-dto';
import { getAllQuestions } from '../fn/esg-controller/get-all-questions';
import { GetAllQuestions$Params } from '../fn/esg-controller/get-all-questions';
import { getEsgQuestionById } from '../fn/esg-controller/get-esg-question-by-id';
import { GetEsgQuestionById$Params } from '../fn/esg-controller/get-esg-question-by-id';
import { getEsgResponses } from '../fn/esg-controller/get-esg-responses';
import { GetEsgResponses$Params } from '../fn/esg-controller/get-esg-responses';
import { getQuestionsByCategory } from '../fn/esg-controller/get-questions-by-category';
import { GetQuestionsByCategory$Params } from '../fn/esg-controller/get-questions-by-category';
import { saveEsgResponse } from '../fn/esg-controller/save-esg-response';
import { SaveEsgResponse$Params } from '../fn/esg-controller/save-esg-response';
import { updateEsgQuestion } from '../fn/esg-controller/update-esg-question';
import { UpdateEsgQuestion$Params } from '../fn/esg-controller/update-esg-question';

@Injectable({ providedIn: 'root' })
export class EsgControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateEsgQuestion()` */
  static readonly UpdateEsgQuestionPath = '/esg/questions/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateEsgQuestion()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEsgQuestion$Response(params: UpdateEsgQuestion$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateEsgQuestion(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateEsgQuestion$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateEsgQuestion(params: UpdateEsgQuestion$Params, context?: HttpContext): Observable<void> {
    return this.updateEsgQuestion$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteEsgQuestion()` */
  static readonly DeleteEsgQuestionPath = '/esg/questions/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteEsgQuestion()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEsgQuestion$Response(params: DeleteEsgQuestion$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteEsgQuestion(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteEsgQuestion$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEsgQuestion(params: DeleteEsgQuestion$Params, context?: HttpContext): Observable<void> {
    return this.deleteEsgQuestion$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getEsgResponses()` */
  static readonly GetEsgResponsesPath = '/esg/responses';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEsgResponses()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEsgResponses$Response(params?: GetEsgResponses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EsgResponsesByCategoryDto>>> {
    return getEsgResponses(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEsgResponses$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEsgResponses(params?: GetEsgResponses$Params, context?: HttpContext): Observable<Array<EsgResponsesByCategoryDto>> {
    return this.getEsgResponses$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EsgResponsesByCategoryDto>>): Array<EsgResponsesByCategoryDto> => r.body)
    );
  }

  /** Path part for operation `saveEsgResponse()` */
  static readonly SaveEsgResponsePath = '/esg/responses';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveEsgResponse()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveEsgResponse$Response(params: SaveEsgResponse$Params, context?: HttpContext): Observable<StrictHttpResponse<EsgResponse>> {
    return saveEsgResponse(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveEsgResponse$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveEsgResponse(params: SaveEsgResponse$Params, context?: HttpContext): Observable<EsgResponse> {
    return this.saveEsgResponse$Response(params, context).pipe(
      map((r: StrictHttpResponse<EsgResponse>): EsgResponse => r.body)
    );
  }

  /** Path part for operation `getAllQuestions()` */
  static readonly GetAllQuestionsPath = '/esg/questions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllQuestions()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllQuestions$Response(params?: GetAllQuestions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EsgQuestionDto>>> {
    return getAllQuestions(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllQuestions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllQuestions(params?: GetAllQuestions$Params, context?: HttpContext): Observable<Array<EsgQuestionDto>> {
    return this.getAllQuestions$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EsgQuestionDto>>): Array<EsgQuestionDto> => r.body)
    );
  }

  /** Path part for operation `createEsgQuestion()` */
  static readonly CreateEsgQuestionPath = '/esg/questions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createEsgQuestion()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEsgQuestion$Response(params: CreateEsgQuestion$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return createEsgQuestion(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createEsgQuestion$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createEsgQuestion(params: CreateEsgQuestion$Params, context?: HttpContext): Observable<void> {
    return this.createEsgQuestion$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getQuestionsByCategory()` */
  static readonly GetQuestionsByCategoryPath = '/esg/questions/{category}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getQuestionsByCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuestionsByCategory$Response(params: GetQuestionsByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EsgQuestionDto>>> {
    return getQuestionsByCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getQuestionsByCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getQuestionsByCategory(params: GetQuestionsByCategory$Params, context?: HttpContext): Observable<Array<EsgQuestionDto>> {
    return this.getQuestionsByCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EsgQuestionDto>>): Array<EsgQuestionDto> => r.body)
    );
  }

  /** Path part for operation `getEsgQuestionById()` */
  static readonly GetEsgQuestionByIdPath = '/esg/question/{questionId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEsgQuestionById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEsgQuestionById$Response(params: GetEsgQuestionById$Params, context?: HttpContext): Observable<StrictHttpResponse<EsgQuestionDto>> {
    return getEsgQuestionById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEsgQuestionById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEsgQuestionById(params: GetEsgQuestionById$Params, context?: HttpContext): Observable<EsgQuestionDto> {
    return this.getEsgQuestionById$Response(params, context).pipe(
      map((r: StrictHttpResponse<EsgQuestionDto>): EsgQuestionDto => r.body)
    );
  }

  /** Path part for operation `calculateEsg()` */
  static readonly CalculateEsgPath = '/esg/calculate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `calculateEsg()` instead.
   *
   * This method doesn't expect any request body.
   */
  calculateEsg$Response(params?: CalculateEsg$Params, context?: HttpContext): Observable<StrictHttpResponse<EsgResultDto>> {
    return calculateEsg(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `calculateEsg$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  calculateEsg(params?: CalculateEsg$Params, context?: HttpContext): Observable<EsgResultDto> {
    return this.calculateEsg$Response(params, context).pipe(
      map((r: StrictHttpResponse<EsgResultDto>): EsgResultDto => r.body)
    );
  }

  /** Path part for operation `deleteEsgResponse()` */
  static readonly DeleteEsgResponsePath = '/esg/responses/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteEsgResponse()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEsgResponse$Response(params: DeleteEsgResponse$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteEsgResponse(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteEsgResponse$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteEsgResponse(params: DeleteEsgResponse$Params, context?: HttpContext): Observable<void> {
    return this.deleteEsgResponse$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
