/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createPaymentIntent } from '../fn/payment-controller/create-payment-intent';
import { CreatePaymentIntent$Params } from '../fn/payment-controller/create-payment-intent';
import { PaymentResponse } from '../models/payment-response';
import { paymentSuccess } from '../fn/payment-controller/payment-success';
import { PaymentSuccess$Params } from '../fn/payment-controller/payment-success';

@Injectable({ providedIn: 'root' })
export class PaymentControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `paymentSuccess()` */
  static readonly PaymentSuccessPath = '/api/payment/payment-success';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `paymentSuccess()` instead.
   *
   * This method doesn't expect any request body.
   */
  paymentSuccess$Response(params: PaymentSuccess$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
    return paymentSuccess(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `paymentSuccess$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  paymentSuccess(params: PaymentSuccess$Params, context?: HttpContext): Observable<{
[key: string]: string;
}> {
    return this.paymentSuccess$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: string;
}>): {
[key: string]: string;
} => r.body)
    );
  }

  /** Path part for operation `createPaymentIntent()` */
  static readonly CreatePaymentIntentPath = '/api/payment/create-payment-intent';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPaymentIntent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPaymentIntent$Response(params: CreatePaymentIntent$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentResponse>> {
    return createPaymentIntent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPaymentIntent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPaymentIntent(params: CreatePaymentIntent$Params, context?: HttpContext): Observable<PaymentResponse> {
    return this.createPaymentIntent$Response(params, context).pipe(
      map((r: StrictHttpResponse<PaymentResponse>): PaymentResponse => r.body)
    );
  }

}
