/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/project-controller/create';
import { Create$Params } from '../fn/project-controller/create';
import { deleteById1 } from '../fn/project-controller/delete-by-id-1';
import { DeleteById1$Params } from '../fn/project-controller/delete-by-id-1';
import { getAll1 } from '../fn/project-controller/get-all-1';
import { GetAll1$Params } from '../fn/project-controller/get-all-1';
import { getByCostLessThan } from '../fn/project-controller/get-by-cost-less-than';
import { GetByCostLessThan$Params } from '../fn/project-controller/get-by-cost-less-than';
import { getById1 } from '../fn/project-controller/get-by-id-1';
import { GetById1$Params } from '../fn/project-controller/get-by-id-1';
import { getPaginatedProjects1 } from '../fn/project-controller/get-paginated-projects-1';
import { GetPaginatedProjects1$Params } from '../fn/project-controller/get-paginated-projects-1';
import { PageProject } from '../models/page-project';
import { Project } from '../models/project';
import { ProjectDto } from '../models/project-dto';
import { searchProjects } from '../fn/project-controller/search-projects';
import { SearchProjects$Params } from '../fn/project-controller/search-projects';
import { update } from '../fn/project-controller/update';
import { Update$Params } from '../fn/project-controller/update';

@Injectable({ providedIn: 'root' })
export class ProjectControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById1()` */
  static readonly GetById1Path = '/project/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById1$Response(params: GetById1$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectDto>> {
    return getById1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById1(params: GetById1$Params, context?: HttpContext): Observable<ProjectDto> {
    return this.getById1$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectDto>): ProjectDto => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/project/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectDto>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<ProjectDto> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProjectDto>): ProjectDto => r.body)
    );
  }

  /** Path part for operation `deleteById1()` */
  static readonly DeleteById1Path = '/project/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteById1()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteById1$Response(params: DeleteById1$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteById1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteById1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteById1(params: DeleteById1$Params, context?: HttpContext): Observable<void> {
    return this.deleteById1$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/project/create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<number> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getAll1()` */
  static readonly GetAll1Path = '/project';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll1$Response(params?: GetAll1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjectDto>>> {
    return getAll1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll1(params?: GetAll1$Params, context?: HttpContext): Observable<Array<ProjectDto>> {
    return this.getAll1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProjectDto>>): Array<ProjectDto> => r.body)
    );
  }

  /** Path part for operation `getPaginatedProjects1()` */
  static readonly GetPaginatedProjects1Path = '/project/paginated';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedProjects1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedProjects1$Response(params?: GetPaginatedProjects1$Params, context?: HttpContext): Observable<StrictHttpResponse<PageProject>> {
    return getPaginatedProjects1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedProjects1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedProjects1(params?: GetPaginatedProjects1$Params, context?: HttpContext): Observable<PageProject> {
    return this.getPaginatedProjects1$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageProject>): PageProject => r.body)
    );
  }

  /** Path part for operation `searchProjects()` */
  static readonly SearchProjectsPath = '/project/filter';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchProjects()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchProjects$Response(params?: SearchProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Project>>> {
    return searchProjects(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchProjects$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchProjects(params?: SearchProjects$Params, context?: HttpContext): Observable<Array<Project>> {
    return this.searchProjects$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Project>>): Array<Project> => r.body)
    );
  }

  /** Path part for operation `getByCostLessThan()` */
  static readonly GetByCostLessThanPath = '/project/cost';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getByCostLessThan()` instead.
   *
   * This method doesn't expect any request body.
   */
  getByCostLessThan$Response(params: GetByCostLessThan$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjectDto>>> {
    return getByCostLessThan(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getByCostLessThan$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getByCostLessThan(params: GetByCostLessThan$Params, context?: HttpContext): Observable<Array<ProjectDto>> {
    return this.getByCostLessThan$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProjectDto>>): Array<ProjectDto> => r.body)
    );
  }

}
