/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteById } from '../fn/transaction-controller/delete-by-id';
import { DeleteById$Params } from '../fn/transaction-controller/delete-by-id';
import { getAll } from '../fn/transaction-controller/get-all';
import { GetAll$Params } from '../fn/transaction-controller/get-all';
import { getById } from '../fn/transaction-controller/get-by-id';
import { GetById$Params } from '../fn/transaction-controller/get-by-id';
import { getPaginatedProjects } from '../fn/transaction-controller/get-paginated-projects';
import { GetPaginatedProjects$Params } from '../fn/transaction-controller/get-paginated-projects';
import { PageTransactionDto } from '../models/page-transaction-dto';
import { save } from '../fn/transaction-controller/save';
import { Save$Params } from '../fn/transaction-controller/save';
import { Transaction } from '../models/transaction';
import { TransactionDto } from '../models/transaction-dto';
import { updateDescription } from '../fn/transaction-controller/update-description';
import { UpdateDescription$Params } from '../fn/transaction-controller/update-description';

@Injectable({ providedIn: 'root' })
export class TransactionControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateDescription()` */
  static readonly UpdateDescriptionPath = '/transaction/{id}/description';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateDescription()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDescription$Response(params: UpdateDescription$Params, context?: HttpContext): Observable<StrictHttpResponse<Transaction>> {
    return updateDescription(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateDescription$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateDescription(params: UpdateDescription$Params, context?: HttpContext): Observable<Transaction> {
    return this.updateDescription$Response(params, context).pipe(
      map((r: StrictHttpResponse<Transaction>): Transaction => r.body)
    );
  }

  /** Path part for operation `save()` */
  static readonly SavePath = '/transaction/create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `save()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  save$Response(params: Save$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return save(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `save$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  save(params: Save$Params, context?: HttpContext): Observable<number> {
    return this.save$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getAll()` */
  static readonly GetAllPath = '/transaction';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll$Response(params?: GetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransactionDto>>> {
    return getAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll(params?: GetAll$Params, context?: HttpContext): Observable<Array<TransactionDto>> {
    return this.getAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransactionDto>>): Array<TransactionDto> => r.body)
    );
  }

  /** Path part for operation `getById()` */
  static readonly GetByIdPath = '/transaction/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById$Response(params: GetById$Params, context?: HttpContext): Observable<StrictHttpResponse<TransactionDto>> {
    return getById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById(params: GetById$Params, context?: HttpContext): Observable<TransactionDto> {
    return this.getById$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransactionDto>): TransactionDto => r.body)
    );
  }

  /** Path part for operation `deleteById()` */
  static readonly DeleteByIdPath = '/transaction/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteById()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteById$Response(params: DeleteById$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteById(params: DeleteById$Params, context?: HttpContext): Observable<void> {
    return this.deleteById$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPaginatedProjects()` */
  static readonly GetPaginatedProjectsPath = '/transaction/paginated';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPaginatedProjects()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedProjects$Response(params?: GetPaginatedProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<PageTransactionDto>> {
    return getPaginatedProjects(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPaginatedProjects$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPaginatedProjects(params?: GetPaginatedProjects$Params, context?: HttpContext): Observable<PageTransactionDto> {
    return this.getPaginatedProjects$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageTransactionDto>): PageTransactionDto => r.body)
    );
  }

}
