spring.application.name=Test-ChatModel
flask.api.url=http://127.0.0.1:5000/
flask.api.url.enterprise=${flask.api.url}generate-recommendations-entreprise
flask.api.url.event=${flask.api.url}generate-recommendations-event
