/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageProject } from '../../models/page-project';

export interface GetPaginatedProjects1$Params {
  skip?: number;
  limit?: number;
}

export function getPaginatedProjects1(http: HttpClient, rootUrl: string, params?: GetPaginatedProjects1$Params, context?: HttpContext): Observable<StrictHttpResponse<PageProject>> {
  const rb = new RequestBuilder(rootUrl, getPaginatedProjects1.PATH, 'get');
  if (params) {
    rb.query('skip', params.skip, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageProject>;
    })
  );
}

getPaginatedProjects1.PATH = '/project/paginated';
