/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectDto } from '../../models/project-dto';

export interface GetByCostLessThan$Params {
  max: number;
}

export function getByCostLessThan(http: HttpClient, rootUrl: string, params: GetByCostLessThan$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjectDto>>> {
  const rb = new RequestBuilder(rootUrl, getByCostLessThan.PATH, 'get');
  if (params) {
    rb.query('max', params.max, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProjectDto>>;
    })
  );
}

getByCostLessThan.PATH = '/project/cost';
