/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Project } from '../../models/project';

export interface SearchProjects$Params {
  name?: string;
  certified?: boolean;
  category?: string;
  mechanism?: string;
  cost?: number;
  country?: string;
}

export function searchProjects(http: HttpClient, rootUrl: string, params?: SearchProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Project>>> {
  const rb = new RequestBuilder(rootUrl, searchProjects.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('certified', params.certified, {});
    rb.query('category', params.category, {});
    rb.query('mechanism', params.mechanism, {});
    rb.query('cost', params.cost, {});
    rb.query('country', params.country, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Project>>;
    })
  );
}

searchProjects.PATH = '/project/filter';
