/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CarbonFootprintHistoryDto } from '../../models/carbon-footprint-history-dto';

export interface ForecastData$Params {
}

export function forecastData(http: HttpClient, rootUrl: string, params?: ForecastData$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CarbonFootprintHistoryDto>>> {
  const rb = new RequestBuilder(rootUrl, forecastData.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CarbonFootprintHistoryDto>>;
    })
  );
}

forecastData.PATH = '/carbonHistory/forecast';
